# Email confirmation keys
SENDGRID_PASSWORD: get_sendgrid_password_from_production
SENDGRID_USERNAME: get_sendgrid_username_from_production
MY_SUPER_SECRET_VARIABLE: secret123456

# Stripe test payment keys
STRIPE_PUBLISHABLE_KEY: pk_test_sI6hblCsplRCbjSN7y4YDBdn
STRIPE_SECRET_KEY: sk_test_VQZZKhCu9BnzaksDPbl6KKG9
SECRET_KEY: secret654321

