# Email confirmation keys
SENDGRID_PASSWORD: get_sendgrid_password_from_production
SENDGRID_USERNAME: get_sendgrid_username_from_production
MY_SUPER_SECRET_VARIABLE: secret123456

# Stripe payment keys
STRIPE_PUBLISHABLE_KEY: get_stripe_publishable_key_from_production
STRIPE_SECRET_KEY: get_stripe_secret_key_from_production
SECRET_KEY: secret918273
